# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a76d2d26518a5f0a74407bf490cb85710fc977afb2710b73322083bc25040313884aa12c770dfbf6bfd63af71fd2b8ce7a2087ac4dceae912a8301bac5423f2

test:
  secret_key_base: 92c0dc523bc52471b87badea085302d4e874b8c751d56ae23a34bf1128e24e8cb97c9ee57342597f581bae98086cc53ccd6688fa7bda09a95fd9ad433be6f8d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
